# Shared dataset configuration for all tasks.
data_root: $DATA_PATH/Gaddy/emg_data/
silent_data_directories:
  - $DATA_PATH/Gaddy/emg_data/silent_parallel_data/
voiced_data_directories:
  - $DATA_PATH/Gaddy/emg_data/voiced_parallel_data/
  - $DATA_PATH/Gaddy/emg_data/nonparallel_data/
h5_path: $DATA_PATH/Gaddy/h5/emg_dataset.h5
normalizers_file: normalizers.pkl
testset_file: testset_largedev.json
text_align_directory: text_alignments
